name: Release
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: simple
          package-name: '@atolye15/stylelint-config'
          changelog-types: '[{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"refactor","section":"Refactors","hidden":false}]'

      - uses: actions/checkout@v6
        if: ${{ steps.release.outputs.release_created }}

      - uses: actions/setup-node@v6
        if: ${{ steps.release.outputs.release_created }}
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'

      - name: Install yarn packages
        if: ${{ steps.release.outputs.release_created }}
        run: yarn

      - name: Publish
        if: ${{ steps.release.outputs.release_created }}
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ env.NPM_TOKEN }}
